2023-08-11 15:44:47.711 | ERROR    | utils:save_prompt:53 - save_label error: [Errno 13] Permission denied: '/0.png'
 Traceback (most recent call last):
  File "/home/lbc/docker_projects/aigc.label.com/utils.py", line 48, in save_prompt
    image.save(save_path)
  File "/home/lbc/miniconda3/envs/webui-dev/lib/python3.10/site-packages/PIL/Image.py", line 2429, in save
    fp = builtins.open(filename, "w+b")
PermissionError: [Errno 13] Permission denied: '/0.png'


2023-08-11 15:45:57.290 | ERROR    | utils:save_prompt:53 - save_label error: [Errno 2] No such file or directory: '/mnt/d/WOA/caches/samples_res/0.png'
 Traceback (most recent call last):
  File "/home/lbc/docker_projects/aigc.label.com/utils.py", line 48, in save_prompt
    image.save(save_path)
  File "/home/lbc/miniconda3/envs/webui-dev/lib/python3.10/site-packages/PIL/Image.py", line 2429, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/d/WOA/caches/samples_res/0.png'


2023-08-11 15:46:28.570 | ERROR    | utils:caption_select_image:42 - caption_select_image error: invalid literal for int() with base 10: ''
 Traceback (most recent call last):
  File "/home/lbc/docker_projects/aigc.label.com/utils.py", line 31, in caption_select_image
    image_info = images[int(image_idx)]
ValueError: invalid literal for int() with base 10: ''


2023-08-11 15:54:18.266 | ERROR    | utils:caption_select_image:42 - caption_select_image error: list index out of range
 Traceback (most recent call last):
  File "/home/lbc/docker_projects/aigc.label.com/utils.py", line 31, in caption_select_image
    image_info = images[int(image_idx)]
IndexError: list index out of range


2023-08-11 16:50:00.077 | ERROR    | utils:caption_select_image:42 - caption_select_image error: list index out of range
 Traceback (most recent call last):
  File "/home/lbc/docker_projects/aigc.label.com/utils.py", line 31, in caption_select_image
    image_info = images[int(image_idx)]
IndexError: list index out of range


2023-08-11 16:53:27.601 | ERROR    | utils:caption_select_image:45 - caption_select_image error: list index out of range
 Traceback (most recent call last):
  File "/home/lbc/docker_projects/aigc.label.com/utils.py", line 34, in caption_select_image
    image_info = images[image_idx]
IndexError: list index out of range


2023-08-11 16:54:10.843 | ERROR    | utils:caption_select_image:45 - caption_select_image error: list index out of range
 Traceback (most recent call last):
  File "/home/lbc/docker_projects/aigc.label.com/utils.py", line 34, in caption_select_image
    image_info = images[image_idx]
IndexError: list index out of range


2023-08-11 16:58:21.732 | ERROR    | utils:caption_select_image:45 - caption_select_image error: list index out of range
 Traceback (most recent call last):
  File "/home/lbc/docker_projects/aigc.label.com/utils.py", line 34, in caption_select_image
    image_info = images[image_idx]
IndexError: list index out of range


2023-08-11 16:59:56.170 | ERROR    | utils:caption_select_image:47 - caption_select_image error: list index out of range
 Traceback (most recent call last):
  File "/home/lbc/docker_projects/aigc.label.com/utils.py", line 36, in caption_select_image
    image_info = images[image_idx]
IndexError: list index out of range


2023-08-11 17:00:04.084 | ERROR    | utils:caption_select_image:47 - caption_select_image error: list index out of range
 Traceback (most recent call last):
  File "/home/lbc/docker_projects/aigc.label.com/utils.py", line 36, in caption_select_image
    image_info = images[image_idx]
IndexError: list index out of range


2023-08-11 17:00:04.744 | ERROR    | utils:caption_select_image:47 - caption_select_image error: list index out of range
 Traceback (most recent call last):
  File "/home/lbc/docker_projects/aigc.label.com/utils.py", line 36, in caption_select_image
    image_info = images[image_idx]
IndexError: list index out of range


2023-08-11 17:00:05.535 | ERROR    | utils:caption_select_image:47 - caption_select_image error: list index out of range
 Traceback (most recent call last):
  File "/home/lbc/docker_projects/aigc.label.com/utils.py", line 36, in caption_select_image
    image_info = images[image_idx]
IndexError: list index out of range


2023-08-11 17:00:05.892 | ERROR    | utils:caption_select_image:47 - caption_select_image error: list index out of range
 Traceback (most recent call last):
  File "/home/lbc/docker_projects/aigc.label.com/utils.py", line 36, in caption_select_image
    image_info = images[image_idx]
IndexError: list index out of range


